name: Multi-Java Build and Upload to Release

on:
  push:
    tags:
      - '*'  # 匹配所有 tags（或 'v*' 匹配 v 开头的 tags）

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['11', '17']  # 支持多个 Java 版本
    name: Build with Java ${{ matrix.java }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'
      
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      
      - name: Upload Artifact (Java ${{ matrix.java }})
        uses: actions/upload-artifact@v4
        with:
          name: Fiora-java${{ matrix.java }}.jar
          path: target/*.jar  # 修改为你的 JAR 路径

  upload-to-release:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
      
      - name: Find Tag Name
        id: get-tag
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "Current tag: $TAG_NAME"
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
      
      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get-tag.outputs.tag_name }}
          files: |
            artifacts/Fiora-java11.jar
            artifacts/Fiora-java17.jar
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
